<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-Academy-edb9f6fc-9234-4cba-8a91-bf0a051a9d3d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Pages\Shared\Partials\_customizer.cshtml" />
    <None Include="Pages\Shared\Partials\_footer.cshtml" />
    <None Include="Pages\Shared\Partials\_head_css.cshtml" />
    <None Include="Pages\Shared\Partials\_Layout.cshtml" />
    <None Include="Pages\Shared\Partials\_menu.cshtml" />
    <None Include="Pages\Shared\Partials\_page_title.cshtml" />
    <None Include="Pages\Shared\Partials\_sidebar.cshtml" />
    <None Include="Pages\Shared\Partials\_title_meta.cshtml" />
    <None Include="Pages\Shared\Partials\_topbar.cshtml" />
    <None Include="Pages\Shared\Partials\_ValidationScriptsPartial.cshtml" />
    <None Include="Pages\Shared\Partials\_vendor_scripts.cshtml" />
    <None Include="Pages\Shared\_AuthLayout.cshtml" />
    <None Include="Pages\Shared\_Layout.cshtml" />
    <None Include="Pages\Shared\_LoginPartial.cshtml" />
    <None Include="Pages\Shared\_SiteLayout.cshtml" />
    <None Include="Pages\Shared\_ValidationScriptsPartial.cshtml" />
  </ItemGroup>

  <ItemGroup>

  
    <PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid.EntityFrameworkAdapter" Version="8.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.6" />
  </ItemGroup>

</Project>
